### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by cocokaribou** [cocokaribou/android_projects#10]
# Android Developer Roadmap

## 4대 컴포넌트
- [x] Activity
- [x] Service
- [ ] Content Provider
- [x] Broadcast Receiver

## Head First Android DeveIopment index (Java)
- [x] ~~Multiple Activities and Intents~~
- [x] ~~The Activity Lifecycle~~
- [x] ~~Views and View Groups~~
- [x] ~~Constraint Layouts~~
- [ ] List Views and Adapters
- [ ] Support Libraries and App Bars
- [x] Fragments - Make It Modular
- [ ] Fragments for Larger Interfaces
- [ ] Dynamic Fragments
- [ ] Design Support Library
- [ ] Recycler Views and Card Views
- [ ] Navigation Drawers
- [ ] SQLite Databases
- [ ] Basic Cursors
- [ ] Cursors and Asynctasks
- [ ] Started Services
- [ ] Bound Services and Permissions
- [ ] Relative and Grid Layouts

## bonus
- [x] Relative and Grid Layouts
- [ ] Gradle - The Gradle Build Tool
- [ ] The Android Runtime
- [ ] The Android Debug Bridge
